name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ssj256x/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e  CI=true ssj256x/react-test npm test
      
      - run: docker build -t ssj256x/multi-client ./client
      - run: docker build -t ssj256x/multi-nginx ./nginx
      - run: docker build -t ssj256x/multi-server ./server
      - run: docker build -t ssj256x/multi-worker ./worker

      - run: docker push ssj256x/multi-client
      - run: docker push ssj256x/multi-nginx
      - run: docker push ssj256x/multi-server
      - run: docker push ssj256x/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-956387521144
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip